server:
  port: ${SERVER_PORT:8080}

logging:
  file:
    name: ${LOG_FILE_DIR:./logs/hrm-backend.log}
  logback:
    rollingPolicy:
      max-file-size: ${LOGBACK_MAX_FILE_SIZE:50MB}
      max-history: ${LOGBACK_MAX_HISTORY:7}
      file-name-pattern: ${logging.file.name}.%d{yyyy-MM-dd}.%i.log
  level:
    org:
      springframework:
        security: ${SERVER_SECURITY_LOG_LEVEL:info}
    web: ${SERVER_WEB_LOG_LEVEL:info}
    root: ${SERVER_ROOT_LOG_LEVEL:info}
spring:
  application:
    name: ${APP_NAME}
  profiles:
    active: ${SPRING_ENV:dev}
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hr_system}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true


  mail:
    host: ${SMTP_SERVER_HOST:localhost}
    port: ${SMTP_SERVER_PORT:25}
    username: ${SMTP_SERVER_USERNAME}
    password: ${SMTP_SERVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SMTP_SERVER_AUTH:false}
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
          starttls.enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    enabled: true

